#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

export MONTHS="January February March April May June July August September October November December"
export TIKA_CMD="/usr/local/tika/tika-app-1.6-SNAPSHOT.jar"
export YEARS="2012 2013 2014"

for month in $MONTHS; 
 do 
    for year in $YEARS;
     do
        url="http://wiki.apache.org/incubator/$month$year"
        if curl --output /dev/null --silent --head --fail "$url"; then
	    java -jar $TIKA_CMD -t "$url" | sniff_mentor.py -t
	fi
    done
done
