#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

export MONTHS="March April May June July August September October November December January February March April"
export TIKA_CMD="/usr/local/tika/tika-app-1.3.jar"

for month in $MONTHS; 
 do 
   if [ "$month" == "March" ] || [ "$month" == "April" ]; then
      year=2012 
      java -jar $TIKA_CMD -t "http://wiki.apache.org/incubator/$month$year" | grep 'Signed off by mentor'
      year=2013
      java -jar $TIKA_CMD -t "http://wiki.apache.org/incubator/$month$year" | grep 'Signed off by mentor'
   else
      year=2012
      java -jar $TIKA_CMD -t "http://wiki.apache.org/incubator/$month$year" | grep 'Signed off by mentor'
   fi
done
