#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

APACHE_PRODUCT=$1
APACHE_VERSION=$2
URL_PREFIX=$3

E_BADARGS=65

if [ $# -ne 3  ]
then
  echo "Usage: `basename $0` <product> <version> <url prefix>"
  exit $E_BADARGS
else
  for ext in tar.gz zip tgz jar; do 
      url=${URL_PREFIX}/${APACHE_PRODUCT}-${APACHE_VERSION}.${ext}
      if curl --output /dev/null --silent --head --fail "$url"; then
	  curl -O ${url}
      fi

      for extra in asc md5 sha1; do
	  url2=${url}.${extra}
	  if curl --output /dev/null --silent --head --fail "$url2"; then
	      curl -O ${url2}
	  fi
      done
  done
fi
