#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Usage:
#   ./verify_md5_checksums [RELEASE_DIRECTORY]

if [ -z "$1" ]; then
    cd $1
fi

cd $1

MD5S="allmd5s.txt"
VERIFY=""
if type md5deep &>/dev/null; then
    echo
    echo "** NOTE ** Using md5deep with -M ..."
    echo "The files that match a known MD5 will be displayed."
    echo "If you don't see an RC artifact something is wrong with the MD5"
    echo

    VERIFY="md5deep -M $MD5S *"
elif type md5sum &>/dev/null; then
    VERIFY="md5sum -c $MD5S"
else
    echo "You don't have an adequate MD5 application. Please install md5sum or md5deep"
fi

echo "Verifying MD5s ..."
for f in *.md5; do
   cat $f >> $MD5S
done

eval $VERIFY
rm -rf $MD5S
